// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5X8M_TC9o_cPi9lsF6UbEc2SvCXTH4Bc',
    appId: '1:481222518079:web:8d469a933e45deb8739f8a',
    messagingSenderId: '481222518079',
    projectId: 'beans-bc9a5',
    authDomain: 'beans-bc9a5.firebaseapp.com',
    storageBucket: 'beans-bc9a5.firebasestorage.app',
    measurementId: 'G-1VSDLWG9NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuiTL3ycPSH--G9M9zHMjSHzhuaLE3rWE',
    appId: '1:481222518079:android:bef01ea8e2a1e6fd739f8a',
    messagingSenderId: '481222518079',
    projectId: 'beans-bc9a5',
    storageBucket: 'beans-bc9a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-zzW0NIDWQ7dL1BO39Qtthg_W-2KFQw',
    appId: '1:481222518079:ios:db102494192d1e59739f8a',
    messagingSenderId: '481222518079',
    projectId: 'beans-bc9a5',
    storageBucket: 'beans-bc9a5.firebasestorage.app',
    iosBundleId: 'com.example.abcd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi-zzW0NIDWQ7dL1BO39Qtthg_W-2KFQw',
    appId: '1:481222518079:ios:db102494192d1e59739f8a',
    messagingSenderId: '481222518079',
    projectId: 'beans-bc9a5',
    storageBucket: 'beans-bc9a5.firebasestorage.app',
    iosBundleId: 'com.example.abcd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5X8M_TC9o_cPi9lsF6UbEc2SvCXTH4Bc',
    appId: '1:481222518079:web:7e9534f022ca574c739f8a',
    messagingSenderId: '481222518079',
    projectId: 'beans-bc9a5',
    authDomain: 'beans-bc9a5.firebaseapp.com',
    storageBucket: 'beans-bc9a5.firebasestorage.app',
    measurementId: 'G-RK7GSEWZEP',
  );
}
